# Generated by Django 3.2.12 on 2022-08-17 19:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name="Project's name")),
                ('customer_name', models.CharField(max_length=128, verbose_name="Customer's name")),
                ('customer_phone', models.CharField(max_length=16, verbose_name="Customer's phone")),
                ('customer_email', models.CharField(max_length=128, verbose_name="Customer's email")),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('pause', 'pause'), ('in progress', 'in progress'), ('stopped', 'stopped')], default='pause', max_length=64, verbose_name="Project's status")),
                ('ready', models.IntegerField(default=0, verbose_name="Project's readiness")),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Project's code")),
                ('imitation_model', models.FileField(blank=True, null=True, upload_to=projects.utils.upload_path_imitation_model)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Room's name")),
                ('status', models.CharField(choices=[('agreed', 'agreed'), ('disagreed', 'disagreed')], default='disagreed', max_length=32, verbose_name="Room's status")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.utils.upload_path_render)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='projects.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.utils.upload_path_panorama)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='projects.room')),
            ],
        ),
    ]
