# Generated by Django 4.1 on 2022-08-04 21:56

from django.db import migrations, models
import projects.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompanorama',
            name='image',
            field=models.ImageField(upload_to=projects.utils.upload_path_panorama),
        ),
        migrations.AlterField(
            model_name='roomrender',
            name='image',
            field=models.ImageField(upload_to=projects.utils.upload_path_render),
        ),
    ]
