# Generated by Django 3.2.12 on 2022-08-18 07:38

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default=users.utils.id_generator, editable=False, max_length=8, primary_key=True, serialize=False, verbose_name="Project's code"),
        ),
    ]
