# Generated by Django 4.1 on 2022-08-05 00:27

from django.db import migrations, models
import projects.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_roompanorama_image_alter_roomrender_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imitation_model',
            field=models.FileField(null=True, upload_to=projects.utils.upload_path_imitation_model),
        ),
    ]
