# Generated by Django 4.1 on 2022-08-09 19:30

from django.db import migrations, models
import projects.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_imitation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imitation_model',
            field=models.FileField(blank=True, null=True, upload_to=projects.utils.upload_path_imitation_model),
        ),
    ]
